### ISSUE TITLE
 Questions about ESC and ESC* dataset

### ISSUE THREAD

**Issue by Z-lemon1** [hrlics/SemDI#1]
作者你好，我注意到你在文中提到ESC与ESC*是不同的，但是获取路径相同。他们的不同是体现在数据集二次处理上吗，想请教一下你是怎么从ESC得到ESC*的。

**Comment by hrlics** [comment]
Hi @Z-lemon1 

Thanks for you question! As mentioned in our paper, ESC* is a different partition setting of the ESC dataset, which involves random shuffling of documents.

**Comment by Z-lemon1** [comment]
> Hi @Z-lemon1
> 
> Thanks for you question! As mentioned in our paper, ESC* is a different partition setting of the ESC dataset, which involves random shuffling of documents.

Thank you very much for your reply. During this time, I experimented on the CTB dataset you provided and did not modify the code. But the experimental results indicated that out of a total of 10 rounds, 8 rounds had 0 results and only 2 rounds had results, one was 50 and one was 33.333. could not reproduce the results you showed in the paper.Experiments on other datasets are fine.
Would like to ask if there is an experimental setup I am overlooking or a reason for this.
My email is: 772762343@qq.com, if it is convenient, you are welcome to communicate with me through email. 
![微信截图_20241221183704](https://github.com/user-attachments/assets/364607d9-5c2a-453b-bd54-633b96cbaaf7)

**Comment by hrlics** [comment]
Hi @Z-lemon1 

Thanks for you question! I think checking your data preprocessing procedure would be helpful. Given the sparsity of causality in the CTB dataset, we apply negative sampling for training with a sampling rate of 0.7, as shown in our implementation details.
